map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.0

robot_radius: 0.3
footprint_padding: -0.0
inflation_radius: 1
cost_scaling_factor: 4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
